apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sharik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: sharikm/malik
        ports:
        - containerPort: 85
