apiVersion: networking.k8s.io/v1
kind: Deploymenyt
metadata:
  name: project-deployment
  labels:
    app: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
  spec:
      containers:
      - name: project
        image: sharikm/malik
        ports:
        - containerPort: 80
